# worklog. last edit 2025-08-19 by jmill
# - tune theme, nav, site_url, repo_url once repo info known
# - initial MkDocs Material config with sidebar ToC and modules scaffold

site_name: Course Companion
site_description: notes, labs, and visualizations for course modules
# update this once the repo is known, e.g., https://<user>.github.io/<repo>/
site_url: https://jmill.github.io/sfumba567-2025Fall/
# optional: show "Edit on GitHub" links once repo is public
edit_uri: edit/main/docs/
repo_url: https://github.com/JMill/sfumba567-2025Fall

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true

use_directory_urls: true

nav:
  - Home: index.md
  - Modules:
      - Chapter 1 (ch1): modules/ch1.md
      - Chapter 2 (ch2): modules/ch2.md
      - Chapter 3 (ch3): modules/ch3.md
      - Chapter 4 (ch4): modules/ch4.md
      - Chapter 5 (ch5): modules/ch5.md
      - Chapter 6 (ch6): modules/ch6.md
      - Chapter 7 (ch7): modules/ch7.md
      - Chapter 8 (ch8): modules/ch8.md
      - Chapter 9 (ch9): modules/ch9.md
  - Embeds: embeds.md
